USE [master]
GO

/****** Object:  Database [IGA-2016-v3]    Script Date: 5/4/2019 7:19:03 PM ******/
CREATE DATABASE [IGA-2016-v3]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IGA-2016-v3', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\IGA-2016-v3.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IGA-2016-v3_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\IGA-2016-v3_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IGA-2016-v3].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [IGA-2016-v3] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET ARITHABORT OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [IGA-2016-v3] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [IGA-2016-v3] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET  DISABLE_BROKER 
GO

ALTER DATABASE [IGA-2016-v3] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [IGA-2016-v3] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [IGA-2016-v3] SET  MULTI_USER 
GO

ALTER DATABASE [IGA-2016-v3] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [IGA-2016-v3] SET DB_CHAINING OFF 
GO

ALTER DATABASE [IGA-2016-v3] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [IGA-2016-v3] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [IGA-2016-v3] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [IGA-2016-v3] SET QUERY_STORE = OFF
GO

ALTER DATABASE [IGA-2016-v3] SET  READ_WRITE 
GO

